version: 2.1

orbs: 
    python: circleci/python@2.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: 
          command: |
            cd hw-02a
            python -m unittest TestTriangle
            cd ..
      - store_test_results:
          path: test-results
  build-and-test-gitapis:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: 
          command: |   
            cd hw-04a
            pip install requests         
            python -m unittest Test_gitapis
            cd ..
      - store_test_results:
          path: test-results

workflows:
  testing_triangles:
    jobs:
      - build-and-test
  testgitapis:
    jobs:
      - build-and-test-gitapis
